# Definition of various test suites
testsuite_1:
  test_configs:                 # You have to define at least one test_config
    - test1
  robots:                       # You have to define at least one robot
    - 2gain_part100_350mm
  robot_envs:                   # You have to define at least one robot_env
    - env1
