# Definition of various test suites
testsuite_1:
  test_configs:                 # You have to define at least one test_config
    - test1
  robots:                       # You have to define at least one robot
   - noopt_100part
 #   - 5opt_25part
 #   - 1mapping_1count
  robot_envs:                   # You have to define at least one robot_env
    - env1
