# Definition of various test suites
testsuite_1:
  test_configs:                 # You have to define at least one test_config
    - test1
  robots:                       # You have to define at least one robot
    - 2gain_part100_350mm
    - 3gain_part100_350mm
    - 5gain_part100_350mm
    - 2gain_part100_400mm
    - 3gain_part100_400mm
    - 5gain_part100_400mm
    - 2gain_part100_450mm
    - 3gain_part100_450mm
    - 5gain_part100_450mm
    - 2gain_part100_500mm
    - 3gain_part100_500mm
    - 5gain_part100_500mm
    - 2gain_part200_350mm
    - 3gain_part200_350mm
    - 5gain_part200_350mm
    - 2gain_part200_400mm
    - 3gain_part200_400mm
    - 5gain_part200_400mm
    - 2gain_part200_450mm
    - 3gain_part200_450mm
    - 5gain_part200_450mm
    - 2gain_part200_500mm
    - 3gain_part200_500mm
    - 5gain_part200_500mm
    - 2gain_part300_350mm
    - 3gain_part300_350mm
    - 5gain_part300_350mm
    - 2gain_part300_400mm
    - 3gain_part300_400mm
    - 5gain_part300_400mm
    - 2gain_part300_450mm
    - 3gain_part300_450mm
    - 5gain_part300_450mm
    - 2gain_part300_500mm
    - 3gain_part300_500mm
    - 5gain_part300_500mm
    - 2gain_part500_350mm
    - 3gain_part500_350mm
    - 5gain_part500_350mm
    - 2gain_part500_400mm
    - 3gain_part500_400mm
    - 5gain_part500_400mm
    - 2gain_part500_450mm
    - 3gain_part500_450mm
    - 5gain_part500_450mm
    - 2gain_part500_500mm
    - 3gain_part500_500mm
    - 5gain_part500_500mm
  robot_envs:                   # You have to define at least one robot_env
    - env1
