# Definition of various test suites
testsuite_1:
  test_configs:                 # You have to define at least one test_config
    - test1
  robots:                       # You have to define at least one robot
    - part200_250mm
    - part200_350mm
    - part200_500mm
    - part200_600mm
    - part200_750mm
    - part100_250mm
    - part100_350mm
    - part100_500mm
    - part100_600mm
    - part100_750mm
    - part150_250mm
    - part150_350mm
    - part150_500mm
    - part150_600mm
    - part150_750mm
    - part75_250mm
    - part75_350mm
    - part75_500mm
    - part75_600mm
    - part75_750mm

  robot_envs:                   # You have to define at least one robot_env
    - env1
