time:
  handler: CalculateTimeParamHandler
path_length:
  handler: CalculatePathLengthParamHandler
resource_cpu:
  handler: CalculateResourcesCpuParamHandler
resource_mem:
  handler: CalculateResourcesMemParamHandler
resource_io:
  handler: CalculateResourcesIOParamHandler
resource_network:
  handler: CalculateResourcesNetworkParamHandler
obstacle_distance:
  handler: CalculateDistanceToObstaclesParamHandler
publish_rate:
  handler: CalculatePublishRateParamHandler
interface:
    handler: CalculateInterfaceParamHandler
# example:
#   handler: ExampleParamHandler